=== Arkkodan/DreamVsDream/schemas/scenes/netplay.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Netplay Scene object",
    "description": "Does not extends Scene base class, have to copy",
    "type": "object",
    "properties": {
        "bgm": {
            "type": "object",
            "properties": {
                "idle": {
                    "type": "string"
                },
                "wait": {
                    "type": "string"
                }
            },
            "required": [
                "idle",
                "wait"
            ]
        },
        "sfx_connect": {
            "type": "object",
            "properties": {
                "start": {
                    "type": "string"
                },
                "success": {
                    "type": "string"
                }
            },
            "required": [
                "start",
                "success"
            ]
        },
        "logo": {
            "type": "string"
        },
        "scanlines": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "object",
                    "properties": {
                        "scanlines": {
                            "type": "string"
                        },
                        "static": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "scanlines",
                        "static"
                    ]
                }
            },
            "required": [
                "image"
            ]
        },
        "menu": {
            "type": "object",
            "properties": {
                "font": {
                    "type": "string"
                },
                "cursorImage": {
                    "type": "string"
                }
            },
            "required": [
                "font",
                "cursorImage"
            ]
        },
        "sfx_tv": {
            "type": "object",
            "properties": {
                "on": {
                    "type": "string"
                },
                "off": {
                    "type": "string"
                }
            },
            "required": [
                "on",
                "off"
            ]
        },

        "images": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": "string"
                    },
                    "pos": {
                        "$ref": "../references.json#/definitions/vec2"
                    },
                    "renderType": {
                        "type": "string",
                        "enum": [
                            "normal",
                            "additive",
                            "subtractive",
                            "multiply"
                        ]
                    },
                    "vel": {
                        "$ref": "../references.json#/definitions/vec2"
                    },
                    "wrap": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "image",
                    "pos"
                ]
            }
        },
        "sound": {
            "type": "object",
            "properties": {
                "menu": {
                    "type": "string"
                },
                "select": {
                    "type": "string"
                },
                "back": {
                    "type": "string"
                },
                "invalid": {
                    "type": "string"
                }
            },
            "required": [
                "menu",
                "select",
                "back",
                "invalid"
            ]
        }
    }
}

=== Arkkodan/DreamVsDream/data/scenes/netplay/netplay.json
{
    "bgm": {
        "idle": "bgm",
        "wait": "waiting"
    },
    "sfx_connect": {
        "start": "get1",
        "success": "get2"
    },
    "sound": {
        "menu": "menu",
        "select": "select",
        "back": "back",
        "invalid": "*invalid"
    },
    "menu": {
        "font": "nes",
        "cursorImage": "cursor"
    },
    "logo": "neslogo",
    "sfx_tv": {
        "on": "on",
        "off": "off"
    },
    "scanlines": {
        "image": {
            "scanlines": "scanlines",
            "static": "static"
        }
    }
}
