=== Arkkodan/DreamVsDream/schemas/stage.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Stage configuration",
    "type": "object",
    "definitions": {
        "stageImageArray": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": "string"
                    },
                    "parallax": {
                        "type": "number"
                    },
                    "round": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 5
                    },
                    "vel": {
                        "$ref": "./references.json#/definitions/vec2"
                    },
                    "wrap": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "image",
                    "parallax"
                ]
            }
        }
    },
    "properties": {
        "imagesAhead": {
            "$ref": "#/definitions/stageImageArray",
            "description": "An array of stage images drawn ahead of characters with some transparency"
        },
        "imagesBehind": {
            "$ref": "#/definitions/stageImageArray",
            "description": "An array of stage images drawn behind characters with full opacity"
        },
        "entities": {
            "type": "object",
            "properties": {
                "w_bounds": {
                    "type": "integer",
                    "description": "Distance players can move from the center to the edge of the stage. Usually half of camera.w"
                },
                "h_ground": {
                    "type": "integer",
                    "description": "Distance from the bottom of the screen where \"ground\" is located"
                }
            },
            "required": [
                "w_bounds",
                "h_ground"
            ]
        },
        "camera": {
            "type": "object",
            "properties": {
                "w": {
                    "type": "integer",
                    "description": "How far the camera can pan from end to end. Usually double of entities.w_bounds"
                },
                "h": {
                    "type": "integer",
                    "description": "How far the camera can pan from end to end"
                }
            },
            "required": [
                "w",
                "h"
            ]
        },
        "bgm": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "intro": {
                        "type": "string"
                    },
                    "loop": {
                        "type": "string"
                    }
                },
                "required": [
                    "loop"
                ]
            },
            "description": "An array of bgm that plays for this stage"
        }
    }
}

=== Arkkodan/DreamVsDream/data/stages/yn_balcony/stage.json
{
    "bgm": [
        {
            "intro": "intro",
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "0.0",
            "parallax": 0.0
        },
        {
            "image": "tv_blank",
            "parallax": 0.6000000238418579,
            "round": 1
        },
        {
            "image": "tv_test",
            "parallax": 0.6000000238418579,
            "round": 2
        },
        {
            "image": "tv_eyeball",
            "parallax": 0.6000000238418579,
            "round": 3
        },
        {
            "image": "tv_kalimba1",
            "parallax": 0.6000000238418579,
            "round": 4
        },
        {
            "image": "tv_kalimba2",
            "parallax": 0.6000000238418579,
            "round": 5
        },
        {
            "image": "bg",
            "parallax": 1.0
        }
    ],
    "imagesAhead": [
        {
            "image": "fg",
            "parallax": 1.0
        },
        {
            "image": "fg2",
            "parallax": 1.0
        }
    ],
    "entities": {
        "h_ground": 40,
        "w_bounds": 320
    },
    "camera": {
        "w": 640,
        "h": 960
    }
}

=== Arkkodan/DreamVsDream/data/stages/yn_masada/stage.json
{
    "bgm": [
        {
            "intro": "intro",
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "0.0",
            "parallax": 0.0,
            "round": 0,
            "vel": {
                "x": 0.5,
                "y": -0.5
            },
            "wrap": true
        },
        {
            "image": "1.0b",
            "parallax": 1.0
        }
    ],
    "imagesAhead": [
        {
            "image": "1.0f",
            "parallax": 1.0
        }
    ],
    "entities": {
        "h_ground": 40,
        "w_bounds": 640
    },
    "camera": {
        "w": 1280,
        "h": 960
    }
}
