=== Arkkodan/DreamVsDream/schemas/stage.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Stage configuration",
    "type": "object",
    "definitions": {
        "stageImageArray": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": "string"
                    },
                    "parallax": {
                        "type": "number"
                    },
                    "round": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 5
                    },
                    "vel": {
                        "$ref": "./references.json#/definitions/vec2"
                    },
                    "wrap": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "image",
                    "parallax"
                ]
            }
        }
    },
    "properties": {
        "imagesAhead": {
            "$ref": "#/definitions/stageImageArray",
            "description": "An array of stage images drawn ahead of characters with some transparency"
        },
        "imagesBehind": {
            "$ref": "#/definitions/stageImageArray",
            "description": "An array of stage images drawn behind characters with full opacity"
        },
        "entities": {
            "type": "object",
            "properties": {
                "w_bounds": {
                    "type": "integer",
                    "description": "Distance players can move from the center to the edge of the stage. Usually half of camera.w"
                },
                "h_ground": {
                    "type": "integer",
                    "description": "Distance from the bottom of the screen where \"ground\" is located"
                }
            },
            "required": [
                "w_bounds",
                "h_ground"
            ]
        },
        "camera": {
            "type": "object",
            "properties": {
                "w": {
                    "type": "integer",
                    "description": "How far the camera can pan from end to end. Usually double of entities.w_bounds"
                },
                "h": {
                    "type": "integer",
                    "description": "How far the camera can pan from end to end"
                }
            },
            "required": [
                "w",
                "h"
            ]
        },
        "bgm": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "intro": {
                        "type": "string"
                    },
                    "loop": {
                        "type": "string"
                    }
                },
                "required": [
                    "loop"
                ]
            },
            "description": "An array of bgm that plays for this stage"
        }
    }
}

=== Arkkodan/DreamVsDream/data/stages/flow_child/stage.json
{
    "bgm": [
        {
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "0.0",
            "parallax": 0.0
        },
        {
            "image": "0.4",
            "parallax": 0.4000000059604645
        },
        {
            "image": "0.6",
            "parallax": 0.6000000238418579
        },
        {
            "image": "1.0",
            "parallax": 1.0
        }
    ],
    "entities": {
        "h_ground": 20,
        "w_bounds": 640
    },
    "camera": {
        "w": 1280,
        "h": 960
    }
}

=== Arkkodan/DreamVsDream/data/stages/yn_sewers/stage.json
{
    "bgm": [
        {
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "1",
            "parallax": 0.6000000238418579,
            "round": 2
        },
        {
            "image": "2",
            "parallax": 0.6000000238418579,
            "round": 3
        },
        {
            "image": "3",
            "parallax": 0.6000000238418579,
            "round": 4
        },
        {
            "image": "4",
            "parallax": 0.6000000238418579,
            "round": 5
        },
        {
            "image": "0.6",
            "parallax": 0.6000000238418579
        },
        {
            "image": "1.0",
            "parallax": 1.0
        }
    ],
    "entities": {
        "h_ground": 30,
        "w_bounds": 640
    },
    "camera": {
        "w": 1280,
        "h": 960
    }
}

=== Arkkodan/DreamVsDream/data/stages/yn_desert/stage.json
{
    "bgm": [
        {
            "loop": "loop"
        },
        {
            "intro": "intro2",
            "loop": "loop2"
        }
    ],
    "imagesBehind": [
        {
            "image": "0.0",
            "parallax": 0.0
        },
        {
            "image": "0.4",
            "parallax": 0.4000000059604645
        },
        {
            "image": "0.8",
            "parallax": 0.800000011920929
        },
        {
            "image": "1.0",
            "parallax": 1.0
        }
    ],
    "imagesAhead": [
        {
            "image": "1.2",
            "parallax": 1.2000000476837158
        }
    ],
    "entities": {
        "h_ground": 30,
        "w_bounds": 640
    },
    "camera": {
        "w": 1280,
        "h": 960
    }
}

=== Arkkodan/DreamVsDream/data/stages/flow_hotel/stage.json
{
    "bgm": [
        {
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "0.0",
            "parallax": 0.0
        },
        {
            "image": "0.4",
            "parallax": 0.4000000059604645
        },
        {
            "image": "0.6_a",
            "parallax": 0.6000000238418579
        },
        {
            "image": "1.0",
            "parallax": 1.0
        }
    ],
    "imagesAhead": [
        {
            "image": "1.2_b",
            "parallax": 1.2000000476837158
        }
    ],
    "entities": {
        "h_ground": 30,
        "w_bounds": 640
    },
    "camera": {
        "w": 1280,
        "h": 960
    }
}

=== Arkkodan/DreamVsDream/data/stages/flow_sugar/stage.json
{
    "bgm": [
        {
            "intro": "intro",
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "0",
            "parallax": 1.0
        },
        {
            "image": "1",
            "parallax": 1.0
        },
        {
            "image": "1kaibutsu",
            "parallax": 1.0,
            "round": 3
        },
        {
            "image": "2",
            "parallax": 1.0
        },
        {
            "image": "2kaibutsu",
            "parallax": 1.0,
            "round": 3
        },
        {
            "image": "3",
            "parallax": 1.0
        }
    ],
    "imagesAhead": [
        {
            "image": "4",
            "parallax": 1.2000000476837158
        }
    ],
    "entities": {
        "h_ground": 20,
        "w_bounds": 426
    },
    "camera": {
        "w": 852,
        "h": 480
    }
}

=== Arkkodan/DreamVsDream/data/stages/yn_dungeon/stage.json
{
    "bgm": [
        {
            "intro": "intro",
            "loop": "loop"
        },
        {
            "intro": "intro2",
            "loop": "loop2"
        }
    ],
    "imagesBehind": [
        {
            "image": "1.0_2",
            "parallax": 1.0
        },
        {
            "image": "1.0",
            "parallax": 1.0,
            "round": 1
        },
        {
            "image": "1.0_2a",
            "parallax": 1.0,
            "round": 2
        },
        {
            "image": "1.0_3a",
            "parallax": 1.0,
            "round": 3
        }
    ],
    "entities": {
        "h_ground": 30,
        "w_bounds": 640
    },
    "camera": {
        "w": 1280,
        "h": 960
    }
}

=== Arkkodan/DreamVsDream/data/stages/flow_white/stage.json
{
    "bgm": [
        {
            "loop": "loop"
        },
        {
            "intro": "intro2",
            "loop": "loop2"
        }
    ],
    "imagesBehind": [
        {
            "image": "1.0",
            "parallax": 1.0
        }
    ],
    "entities": {
        "h_ground": 30,
        "w_bounds": 448
    },
    "camera": {
        "w": 896,
        "h": 672
    }
}

=== Arkkodan/DreamVsDream/data/stages/flow_rot/stage.json
{
    "bgm": [
        {
            "loop": "loop"
        }
    ],
    "imagesBehind": [
        {
            "image": "0.4b",
            "parallax": 1.0
        }
    ],
    "imagesAhead": [
        {
            "image": "0.4f",
            "parallax": 1.0
        }
    ],
    "entities": {
        "h_ground": 30,
        "w_bounds": 336
    },
    "camera": {
        "w": 672,
        "h": 896
    }
}
